apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prod
  labels:
    app: url-shortener
    tier: backend
spec:
  type: {{.Values.service.type}}
  selector:
    app: url-shortener
    tire: backend
  ports:
  - protocol: TCP
    port: {{.Values.service.backendPort}}
    targetPort: {{.Values.service.backendPort}}
  
  