apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
  labels:
    app: url-shortener
    tier: frontend
spec:
  type: {{.Values.service.type}}
  selector:
    app: url-shortener
    tire: frontend
  ports:
  - protocol: TCP
    port: {{.Values.service.frontendPort}}
    targetPort: {{.Values.service.frontendPort}}
  
