apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: prod
  labels:
    app: url-shortener
    tier: database
spec:
  type: ClusterIP
  selector:
    app: url-shortener
    tire: database
  ports:
  - name: mongo-service
    protocol: TCP
    port: 27017
    targetPort: 27017
  
