apiVersion: v1 
kind: Secret
metadata:
  name: mongo-secret
  namespace: prod
  labels:
    app: url-shortener
    tire: database
type: Opaque
data:
  username: bW9uZ29hZG1pbg==
  password: cGFzc3dvcmQ=