apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: prod
  labels:
    app: url-shortener
    tire: database 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      tire: database
  template:
    metadata:
      labels: 
        app: url-shortener
        tire: database
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 27017
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
    volumes:
      - name: mongo-storage
        persistentVolumeClaim: 
          claimName: mongo-pvc 
       