# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

# Set the MongoDB data directory
VOLUME /data/db

# Expose the MongoDB port
EXPOSE 27017

# Set the default command to run MongoDB
CMD ["mongod"]
