name: Docker Image CI

on:
  push:
    branches: [ "frontend" ]
  pull_request:
    branches: [ "frontend" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    # Build and start the Docker services
    - name: Build and start the Docker services
      run: docker-compose up --build
